### PR TITLE
Blogpost: issue#57/author smackdown

### PR DESCRIPTION
**Pull request by jonnybazookatone**
ok, annoying branch rename. Can you make this (or give comments to make it) funnier @aholachek.

### CODE REVIEW

**Comment by aholachek** [comment]
here is the link for the javascript: https://github.com/aholachek/smackdown

otherwise it looks good to me

although I take some issue with "cliched title"

**Comment by jonnybazookatone** [comment]
Hmmm, I guess at the bottom I should give the correct trade mark info for the WWE images.

**Comment by aaccomazzi** [comment]
Some fixes to the code samples:

1. ads.TOKEN should be ads.config.token (but why use it if the recipe is to set ADS_DEV_TOKEN)?
2. ads.SolrQuery should be ads.SearchQuery
3. missing quote after "riq" below:
riq = metrics_response['indicators']['riq']
4. to get citations back, you would add 'citation' to fl, not 'citations'

Other comments: 

1. technically it's not true that asking for 'citation' does a second order operation, but it just requires additional data to be retrieved and serialized
2. I noticed that if one just asks for fl=['id','bibcode'] you cannot print the objects which come back (because it uses 'first_author' which we didn't request); is this confusing to a user?
3. I'm nitpicking here but I would name the result of the ads.SearchQuery call solr_query since the user does not need to know or care what solr is.  Maybe "ads_query" or just "query"

**Comment by jonnybazookatone** [comment]
Comments implemented. I didn't address "you cannot print objects which come back without first_author". I think if they get that far they can figure it out. However, it can go on the list of changes we want to make PRs for in the client for "errorless user experiences".

**Pull request merged**
